/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.lmarianski.avraeplus;

import java.util.ArrayList;
import java.util.stream.Collectors;

import com.mongodb.*;

import org.javacord.api.*;
import org.javacord.api.entity.channel.TextChannel;
import org.javacord.api.entity.message.embed.EmbedBuilder;
import org.javacord.api.entity.permission.PermissionType;
import org.javacord.api.entity.server.Server;
import org.javacord.api.entity.user.User;
import org.javacord.api.event.message.*;

import de.btobastian.sdcf4j.Command;
import de.btobastian.sdcf4j.CommandExecutor;
import de.btobastian.sdcf4j.CommandHandler;
import de.btobastian.sdcf4j.handler.JavacordHandler;

public class Main implements CommandExecutor {

    public static final String DISCORD_BOT_TOKEN = "@discordBotToken@";

    public static DiscordApi bot;
    public static CommandHandler cmdHandler;
    public static MongoClient mongoClient;

    public static DB serverTomeDB;

    public static void main(String[] args) {
        mongoClient = new MongoClient();
        serverTomeDB = mongoClient.getDB("serverTomeDB");

        bot = new DiscordApiBuilder().setToken(DISCORD_BOT_TOKEN).login().join();
        cmdHandler = new JavacordHandler(bot);

        cmdHandler.setDefaultPrefix("//");

        cmdHandler.registerCommand(new Main());
    }

    public static ArrayList<String> getServerTomes(final Server server) {
        DBCollection serverCol = serverTomeDB.getCollection(server.getIdAsString());

        ArrayList<String> list = new ArrayList<String>(serverCol.find().toArray().stream().map(el -> el.get("_id")).collect(Collectors.toList()));

        return list;
    }

    @Command(aliases = "addtome", description = "Adds a tome to this bots database for this server")
    public void onAddTomeCommand(String[] args, Server server) throws Exception {
        DBCollection serverCol = serverTomeDB.getCollection(server.getIdAsString());

        serverCol.insert(new BasicDBObject("_id", args[0]));
    }

    @Command(aliases = "listtomes", description = "Adds a tome to this bots database for this server")
    public void onListTomes(String[] args, Server server, TextChannel channel) throws Exception {
        channel.sendMessage(new EmbedBuilder()
        .setDescription(String.join("\n", getServerTomes(server))));
    }

    @Command(aliases = {"spelllist", "spells", "sl"}, description = "Pong!")
    public void onSpellListCommand(String[] args) throws Exception {
        
    }

}
